<template>
    <div id="login-debugger">
        <h2>Login Debugger</h2>
        <div>
            <h3>Challenge</h3>
            <p class="small">Randomly generated by server. To be signed with derivated RSA privateKey</p>
            <pre>{{challengeJSON}}</pre>
        </div>
        <div>
            <h3>key Derivation Options</h3>
            <p class="small">Received from server. Stored at last user password change</p>
            <pre>{{keyDerivatorJSON}}</pre>
        </div>
        <div>
            <h3>Key pair</h3>
            <p class="small">Derivated from Password and Salt by front-end</p>
            <pre>{{keypairRsaJSON}}</pre>
        </div>
        <div><h3>Encoded Signature</h3>
            <p class="small">Challenge signature using derivated Private key</p>
            <pre>{{encodedSignature}}</pre>
        </div>
    </div>
</template>

<script>
    import forge from "node-forge"
  export default {
    name: "login-debugger",
    props:[
      "challenge",
      "keyDerivator",
      "authManagerDebugOutput"
    ],
    computed: {
      keyDerivatorJSON(){return this.stringify(this.keyDerivator)},
      challengeJSON(){return this.stringify(this.challenge)},
      keypairRsaJSON(){
        return this.stringify(this.authManagerDebugOutput.keypair)
      },
      encodedSignature(){
        return this.authManagerDebugOutput.signature.encoded;
      }
    },
    methods:{
      stringify(v){return JSON.stringify(v, null, 2);}
    }
  }
</script>

<style scoped>
    .small {
        font-size: 0.8em;
    }
</style>